export const TOOLS = [
  {
    id: 'business-health-score',
    name: 'Business Health Score',
    description: 'Get a comprehensive score across 5 dimensions: Data, Operations, Technology, Finance, and Marketing. Receive personalised recommendations.',
    href: '/tools/business-health-score',
    status: 'live',
    icon: 'BarChart3',
    time: '8 minutes',
    badge: 'Free',
  },
  {
    id: 'cash-flow-forecaster',
    name: 'Cash Flow Forecaster',
    description: 'Model your next 90 days of cash flow with scenario planning for best, base, and worst cases.',
    href: '#',
    status: 'comingSoon',
    icon: 'TrendingUp',
    time: '5 minutes',
    badge: 'Coming Soon',
  },
  {
    id: 'process-efficiency-audit',
    name: 'Process Efficiency Audit',
    description: 'Identify your top 3 operational bottlenecks and quantify the cost of manual work.',
    href: '#',
    status: 'comingSoon',
    icon: 'Settings',
    time: '10 minutes',
    badge: 'Coming Soon',
  },
  {
    id: 'tech-stack-evaluator',
    name: 'Tech Stack Evaluator',
    description: 'Assess whether your current software stack is holding you back or setting you up for scale.',
    href: '#',
    status: 'comingSoon',
    icon: 'Cpu',
    time: '6 minutes',
    badge: 'Coming Soon',
  },
  {
    id: 'kpi-builder',
    name: 'KPI Builder',
    description: 'Build a bespoke KPI framework for your industry and company stage in minutes.',
    href: '#',
    status: 'comingSoon',
    icon: 'Target',
    time: '7 minutes',
    badge: 'Coming Soon',
  },
  {
    id: 'roi-calculator',
    name: 'Analytics ROI Calculator',
    description: 'Calculate the expected return on investment from implementing a proper analytics system.',
    href: '#',
    status: 'comingSoon',
    icon: 'Calculator',
    time: '3 minutes',
    badge: 'Coming Soon',
  },
  {
    id: 'data-readiness-checker',
    name: 'Data Readiness Checker',
    description: 'Find out if your data infrastructure is ready for AI and machine learning applications.',
    href: '#',
    status: 'comingSoon',
    icon: 'Database',
    time: '5 minutes',
    badge: 'Coming Soon',
  },
]
