export const TOOLS = [
  {
    id: 'business-health-score',
    name: 'Business Health Score',
    description: 'Score your business across 5 dimensions',
    href: '/tools/business-health-score',
    status: 'live',
    icon: 'BarChart3',
    time: '8 min',
    badge: 'Free',
  },
  {
    id: 'ai-readiness-assessment',
    name: 'AI Readiness Assessment',
    description: 'Find out if your business is ready for AI',
    href: '/tools/ai-readiness-assessment',
    status: 'live',
    icon: 'Brain',
    time: '6 min',
    badge: 'Free',
  },
  {
    id: 'dashboard-roi-calculator',
    name: 'Dashboard ROI Calculator',
    description: 'Calculate the ROI of a live dashboard',
    href: '/tools/dashboard-roi-calculator',
    status: 'live',
    icon: 'Calculator',
    time: '3 min',
    badge: 'Free',
  },
  {
    id: 'operational-cost-leak',
    name: 'Operational Cost Leak Calculator',
    description: 'Find hidden operational waste',
    href: '/tools/operational-cost-leak',
    status: 'live',
    icon: 'TrendingDown',
    time: '5 min',
    badge: 'Free',
  },
  {
    id: 'data-maturity-assessment',
    name: 'Data Maturity Assessment',
    description: 'Measure your data infrastructure maturity',
    href: '/tools/data-maturity-assessment',
    status: 'live',
    icon: 'Database',
    time: '7 min',
    badge: 'Free',
  },
  {
    id: 'excel-dependency-score',
    name: 'Excel Dependency Score',
    description: 'Discover your Excel risk exposure',
    href: '/tools/excel-dependency-score',
    status: 'live',
    icon: 'Table',
    time: '4 min',
    badge: 'Free',
  },
  {
    id: 'kpi-maturity-score',
    name: 'KPI Maturity Score',
    description: 'Assess your KPI framework completeness',
    href: '/tools/kpi-maturity-score',
    status: 'live',
    icon: 'Target',
    time: '6 min',
    badge: 'Free',
  },
]
